language: php

php:
- '7.3'
- '7.4'

os: linux

before_script:
- touch database/test.sqlite
- composer install
- cp .env.testing .env
- php artisan key:generate
- php artisan --env=testing migrate:fresh --seed

script:
- php artisan test